### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by mstuttgart** [multidadosti-erp/others-addons#22]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] ~ckeditor_widget~ (Módulo não utilizado)
- [x] ~colored_field_widget~ (Módulo não utilizado)
- [x] document_attachment_manage @rodrigets https://github.com/multidadosti-erp/others-addons/pull/31
- [x] ~git_info~
- [x] ~inputmask_widget~ (Módulo não utilizado)
- [x] int_range_widget @rodrigets https://github.com/multidadosti-erp/others-addons/pull/33
- [x] partner2user @rodrigets https://github.com/multidadosti-erp/others-addons/pull/23
- [x] ~partner_external_map~
- [x] postit_systray_menu @rodrigets https://github.com/multidadosti-erp/others-addons/pull/30
- [x] prisme_postit @mstuttgart https://github.com/multidadosti-erp/others-addons/pull/29
- [x] tko_contacts @rodrigets https://github.com/multidadosti-erp/others-addons/pull/28
- [x] ~tko_partner_multiple_addresses~ (Não utilizado)
- [x] tko_partner_multiple_emails @rodrigets https://github.com/multidadosti-erp/others-addons/pull/28
- [x] tko_partner_multiple_phones @rodrigets https://github.com/multidadosti-erp/others-addons/pull/28
- [x] ~vieterp_mailbox~
- [x] visible_search_menu @rodrigets https://github.com/multidadosti-erp/others-addons/pull/32
- [ ] web_groupby_expand
- [x] web_lead_funnel_chart @rodrigets https://github.com/multidadosti-erp/others-addons/pull/35
- [x] web_list_view_count @rodrigets https://github.com/multidadosti-erp/others-addons/pull/34
- [x] ~web_slider_widget~ (Módulo não utilizado)
